parameters:
    searchify.service.class  : TE\SearchifyBundle\Service\SearchifyService
    searchify.listener.class : TE\SearchifyBundle\Listener\SearchifyListener

    searchify:
        private_url       : ~
        public_url        : ~
        main_index        : ~
        scoring_functions : ~