services:
    searchify:
        class:   "%searchify.service.class%"
        arguments:
            - "%searchify%"

    searchify.listener:
        class:   "%searchify.listener.class%"
        arguments:
            - @searchify
            - @doctrine.orm.entity_manager
        tags:
            # so it reads the method getSubscribedEvents()
            - { name: kernel.event_subscriber }
